# Taskfile.yml
version: '3'

tasks:
  default:
    desc: "Instructions to run the development servers"
    cmds:
      - echo "Run 'task dev:backend' and 'task dev:frontend' in separate terminals."

  install:
    desc: "Install all project dependencies (backend and frontend)"
    cmds:
      - task: install:backend
      - task: install:frontend

  install:backend:
    desc: "Install backend Python dependencies using uv"
    cmds:
      - uv sync
    sources:
      - pyproject.toml
      - uv.lock

  install:frontend:
    desc: "Install frontend Node.js dependencies"
    cmds:
      - npm install --prefix src/frontend
    sources:
      - src/frontend/package.json

  dev:backend:
    desc: "Run the backend development server (FastAPI)"
    cmds:
      - uv run -- uvicorn src.backend.main:app --reload

  dev:frontend:
    desc: "Run the frontend development server (Vite)"
    cmds:
      - npm run dev --prefix src/frontend

  update-roster:
    desc: "Update the player roster table in the README.md"
    cmds:
      - uv run scripts/generate_roster_table.py
